# From Raw Employee Reviews to Workplace Insight: Cleaning and Analyzing Glassdoor Job Reviews

## Introduction

Employee reviews provide a unique perspective on workplace quality because they combine numeric evaluations with direct written opinions from workers. These reviews can reveal patterns, related to compensation, work-life balance, management quality and overall employee satisfaction. At the same time, data is often inconsistent and noisy, which makes careful preprocessing essential before any meaningful conclusions can be drawn.\
The aim of this project is to transform a large raw Glassdoor dataset into reliable analytical dataset and to investigate which workplace factors are most strongly associated with positive and negative employee evaluations. In addition to exploratory and comparative analysis, the project also emphasizes practical data-science work such as auditing, missing-value treatment, categorical standartization and text-preprocessing.\
To place the findings in broader context, the analysis is supplemented with a second independent source ocntaining macroeconomic indicators. This allows the project to connect individual workspace reviews with wider economic conditions while preserving the main analytical focus on individual employee review data.

## Problem Formulation

### Problem Statement

Online employee reviews provide a valuable but imperfect source of information about workplace quality. They combined structured evaluation metrics such as ratings for work-life balance, compensation and management with unstructured text fields containing personal experience and opinions. This makes them highly informative, but also difficult to analyze directly because the data may contain missing values, inconsistent categories, noisy text, duplicated entries and other quality issues.\
The central problem of this project is how to transform a large raw employee-review dataset into reliable analytical dataset and use it to extraxt meaningful insights about workplace satisfaction and dissatisfaction. The project focuses not only on identifying patterns in employee evaluations, but also on demonstrating a full data science workflow: data auditing, cleaning, preprocessing, exploratory analysis and interpretation.\
More specifically, the analysis aims to examine which workplace factors are more strongly associated with positive and negative overall evaluations, whether current and former employees differs in their assessments and what themes are most common in positive and negative textual feedback. A secondary data source is included to provide more broarder economic context, but the main analytical focus will remain n the Glassdoor review data.

### Research questions

1. What data quality issues are present in Glassdoor employee review dataset and how they can be treated appropriately?
2. Which structured workplace factors are most strongly associated with overall employee ratings?
3. Do current and former employees evaluate their workplaces differently?
4. What are most common themes in positive and negative textual reviews?
5. How can broader economic conditions help contextualise employee perceptions of compensation, benefits and workplace quality?

### Hypotheses

**H1.** Higher ratings for work-life balance, compensation and benefits, career opportunities and senior management are assosiated with higher overall employee ratings.\
**H2.** Former employees tend to leave less favorable reviews than current employees.\
**H3.** Negative textual reviews more frequently emphasize themes related to poor management, heavy workload, limited career growth and dissatisfaction with compensation.\
**H4.** Positive textual reviews more often emphasize flexibility, supportive colleagues, benefits and workplace culture.\
**H5.** Broader iconomic pressure may be reflected in strong dissatisfaction with compensation-related aspects of work, although this relationship should be interpreted as contextual rather than causal.

## Data Sources

This project uses two independent data sources.

The main source is the **Glassdoor Job Reviews** dataset obtained from Kaggle. It contains large number of employee reviews and combines structured evaluation variables with unstructured textual feedback. The structured variables inlcude measures such as overall rating, work-life balance, compensation and benefits, career opportunities, senior management evaluation, recommendation indicators and employment status. In addition, the dataset includes text-free fields such as review headlines, pros and cons. This makes it suitable both for workplace analysis and for demonstrating data-cleaning and preprocessing techniques.\
The second source is macroeconomic dataset obtained from the **World Bank World Development Indicators** database. It includes selected indicators such as inflation, GDP growth and unemployment rates for set of countries in time period 2010-2025. Unlike the Glassdoor dataset, this set is not used for individual-level analysis. Instead, it serves a supporting role by providing broader economic context for the interpretation of employee review patterns.

### Methodology

The analytical workflow of this project follows the OSEMN framework: obtaining the data, scrubbing and preprocessing it, exploring its structure and patterns, applying analytical methods and intepreting the results. In practice, the methodology is adapted to the specific characteristics of the datasets used in the project.\
The analysis begins with loading the datasets and performing initial inspection in order to understand their structure, variable types and potential data quality issues. This is followed by data-cleaning and preprocessing stage, where missing values, duplicated observations, inconsistent categorical labels and noisy text fields are identified and treated appropriately.\
After the data has been prepared, the project proceeds with exploratory data analysis in order to examine the distribution of key variables and the relationship between key workplace factors and overall employee evaluations. Particular attention is given to current and former employees, as well as to the relationship between structured ratings and text-free feedback.\
The textual fields are then processed separately in order to identify common themes in positive and negative review. Finally, the World Bank dataset is used to provide broader economic context for the interpretation of the review-based findings. The results are discussed with attention to the limitations of the data and the scope of the conclusions that can be reasonably drawn.

### Data Loading and Initial Inspection

The first practical step of the analysis is to load the datasets and inspect their structure, dimensions, variables types and initial data quality characteristics.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
glassdoor_reviews = pd.read_csv("glassdoor_reviews.csv")

In [4]:
glassdoor_reviews.shape

(838566, 18)

In [5]:
glassdoor_reviews.head(5)

,firm,date_review,job_title,current,location,overall_rating,work_life_balance,culture_values,diversity_inclusion,career_opp,comp_benefits,senior_mgmt,recommend,ceo_approv,outlook,headline,pros,cons
0,AFH-Wealth-Management,2015-04-05,,Current Employee,NaN,2,4.0,3.0,NaN,2.0,3.0,3.0,x,o,r,"Young colleagues, poor micro management",Very friendly and welcoming to new staff. Easy...,"Poor salaries, poor training and communication."
1,AFH-Wealth-Management,2015-12-11,Office Administrator,"Current Employee, more than 1 year","Bromsgrove, England, England",2,3.0,1.0,NaN,2.0,1.0,4.0,x,o,r,"Excellent staff, poor salary","Friendly, helpful and hard-working colleagues",Poor salary which doesn't improve much with pr...
2,AFH-Wealth-Management,2016-01-28,Office Administrator,"Current Employee, less than 1 year","Bromsgrove, England, England",1,1.0,1.0,NaN,1.0,1.0,1.0,x,o,x,"Low salary, bad micromanagement",Easy to get the job even without experience in...,"Very low salary, poor working conditions, very..."
3,AFH-Wealth-Management,2016-04-16,,Current Employee,NaN,5,2.0,3.0,NaN,2.0,2.0,3.0,x,o,r,Over promised under delivered,Nice staff to work with,No career progression and salary is poor
4,AFH-Wealth-Management,2016-04-23,Office Administrator,"Current Employee, more than 1 year","Bromsgrove, England, England",1,2.0,1.0,NaN,2.0,1.0,1.0,x,o,x,client reporting admin,"Easy to get the job, Nice colleagues.","Abysmal pay, around minimum wage. No actual tr..."

In [6]:
glassdoor_reviews.dtypes

firm                    object
date_review             object
job_title               object
current                 object
location                object
overall_rating           int64
work_life_balance      float64
culture_values         float64
diversity_inclusion    float64
career_opp             float64
comp_benefits          float64
senior_mgmt            float64
recommend               object
ceo_approv              object
outlook                 object
headline                object
pros                    object
cons                    object
dtype: object

The initial inspection shows that the dataset contains both structured and unstructured variables. At this tage, main goal is to identify potential data quality issues such as missing values, duplicated observations, inconsistent formats and variables that may require type conversion.

In [7]:
glassdoor_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 838566 entries, 0 to 838565
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   firm                 838566 non-null  object
 1   date_review          838566 non-null  object
 2   job_title            838566 non-null  object
 3   current              838566 non-null  object
 4   location             541223 non-null  object
 5   overall_rating       838566 non-null  int64
 6   work_life_balance    688672 non-null  float64
 7   culture_values       647193 non-null  float64
 8   diversity_inclusion  136066 non-null  float64
 9   career_opp           691065 non-null  float64
 10  comp_benefits        688484 non-null  float64
 11  senior_mgmt          682690 non-null  float64
 12  recommend            838566 non-null  object
 13  ceo_approv           838566 non-null  object
 14  outlook              838566 non-null  object
 15  headline             835976 non-null  object
 16  pros                 838564 non-null  object
 17  cons                 838553 non-null  object
dtypes: float64(6), int64(1), object(11)
memory usage: 115.2+ MB

In [8]:
glassdoor_reviews.isna().sum().sort_values(ascending=False)

diversity_inclusion    702500
location               297343
culture_values         191373
senior_mgmt            155876
comp_benefits          150082
work_life_balance      149894
career_opp             147501
headline                 2590
cons                       13
pros                        2
date_review                 0
overall_rating              0
current                     0
recommend                   0
ceo_approv                  0
outlook                     0
job_title                   0
firm                        0
dtype: int64

The initial inspection shows that several columns contain substantial missingness. While some variables such as firm, job_title, outlook, date_review, overall_rating, etc. appear complete, others, including diversity_inclusion and location, contain large number of missing values and will require careful treatment.

In [9]:
glassdoor_reviews.duplicated().sum()

np.int64(33515)

In [10]:
glassdoor_reviews.nunique().sort_values()

recommend                   3
outlook                     4
ceo_approv                  4
diversity_inclusion         5
overall_rating              5
work_life_balance           5
culture_values              5
senior_mgmt                 5
career_opp                  5
comp_benefits               5
current                    29
firm                      428
date_review              4813
location                14486
job_title               62275
headline               390454
cons                   777133
pros                   778559
dtype: int64

### Recoding Categorical Variables

In [11]:
for col in ['current', 'recommend', 'ceo_approv', 'outlook']:
    print(f"\nColumn: {col}")
    print(glassdoor_reviews[col].value_counts(dropna=False))

Column: current
current
Current Employee                           209599
Former Employee                            146133
Current Employee, more than 1 year          82749
Current Employee, more than 3 years         66471
Former Employee, more than 1 year           65687
Current Employee, less than 1 year          49603
Former Employee, more than 3 years          43614
Former Employee, less than 1 year           41874
Current Employee, more than 5 years         40155
Current Employee, more than 10 years        25029
Former Employee, more than 5 years          23017
Current Employee, more than 8 years         18506
Former Employee, more than 10 years         15411
Former Employee, more than 8 years          10686
Former Contractor, less than 1 year             6
Former Intern, less than 1 year                 5
Current Contractor, less than 1 year            3
Current Contractor, more than 1 year            3
Former Contractor                               2
Current Contractor                              2
Former Intern                                   2
KEY NOT FOUND: jobLine.per_diem-former          2
Former Intern, more than 1 year                 1
Current Intern, less than 1 year                1
Former Contractor, more than 1 year             1
Former Contractor, more than 8 years            1
Former Temporary Employee                       1
Current Freelancer, more than 3 years           1
KEY NOT FOUND: jobLine.temporary-former         1
Name: count, dtype: int64

Column: recommend
recommend
v    427865
o    234248
x    176453
Name: count, dtype: int64

Column: ceo_approv
ceo_approv
o    311433
v    286695
r    176930
x     63508
Name: count, dtype: int64

Column: outlook
outlook
v    301413
o    294548
r    154948
x     87657
Name: count, dtype: int64

The columns **recommend**, **ceo_approv** and **outlook** are encoded categorical variables representing employee endorsment, CEO approval and business outlook. According to the dataset description in Kaggle, the encoded values correspond for **v - Positive, r - Mild, x - Negative and o - No opinion.** This categories needs to be encoded into readable categories before further analysis.

In [12]:
glassdoor_reviews['recommend'] = glassdoor_reviews['recommend'].replace({
    'v':'Positive',
    'o':'No opinion',
    'x':'Negative'})

In [16]:
glassdoor_reviews['ceo_approv'] = glassdoor_reviews['ceo_approv'].replace({
    'v':'Positive',
    'r':'Mild',
    'o':'No opinion',
    'x':'Negative'})

In [17]:
glassdoor_reviews['outlook'] = glassdoor_reviews['outlook'].replace({
    'v':'Positive',
    'r':'Mild',
    'o':'No opinion',
    'x':'Negative'})

The original current column contains multiple variants combining employment status and tenure information. To improve interpretability, a new variable called employee_status was created with three categories: Current, Former, and Other. The recoding shows that almost all observations fall into the first two categories, while only a negligible number of records remain classified as Other.

In [28]:
glassdoor_reviews['employee_status'] = np.where(glassdoor_reviews['current'].str.contains('Current', na = False), 'Current', np.where(glassdoor_reviews['current'].str.contains('Former', na = False), 'Former', 'Other'))

In [37]:
glassdoor_reviews[glassdoor_reviews['employee_status']=='Other']

,firm,date_review,job_title,current,location,overall_rating,work_life_balance,culture_values,diversity_inclusion,career_opp,comp_benefits,senior_mgmt,recommend,ceo_approv,outlook,headline,pros,cons,employee_status
787336,UHMBT,2020-11-17,MLA,KEY NOT FOUND: jobLine.per_diem-former,"Lancaster, England, England",4,3.0,4.0,4.0,2.0,3.0,4.0,Positive,Mild,Positive,"fair employer, very good working condition","fair employer, very good working condition",hard to move on with your career,Other
826279,Western-Health-and-Social-Care-Trust,2020-05-23,Registered Nurse,KEY NOT FOUND: jobLine.per_diem-former,"Omagh, Northern Ireland, Northern Ireland",5,NaN,NaN,NaN,NaN,NaN,NaN,No opinion,No opinion,No opinion,Good to staff,Good experience as a staff nurse,Took a while to solve issues,Other
826282,Western-Health-and-Social-Care-Trust,2020-10-04,Sales Assistant,KEY NOT FOUND: jobLine.temporary-former,"Derry, Northern Ireland, Northern Ireland",3,3.0,3.0,3.0,4.0,3.0,3.0,Positive,Positive,Positive,Good job,Helping people with my degree,Contract was only temporary so I had to be let go,Other

In [29]:
glassdoor_reviews.employee_status.value_counts()

employee_status
Current    492122
Former     346441
Other           3
Name: count, dtype: int64